### ISSUE TITLE
Recipe for Sulfuric Light Fuel to Light Fuel in Chemical Reactor is unavailable.

### ISSUE THREAD

**Issue by openipka** [Shadows-of-Fire/Shadows-of-Greg#105]
**Mod Used**
gregtech-1.12.2-1.11.1.632
gregtech-1.12.2-1.11.1.632-energy-api
gregtech-1.12.2-1.11.1.632-source
Shadows_of_Greg-1.12.2-2.15.0
CodeChickenLib-1.12.2-3.2.3.358-universal

**Issue**
1. Unable to produce Light Fuel through vanilla process of reaction in chemical reactor by desulfurization of Sulfuric Light Fuel. Also , Heavy Fuel, Gas and Naphtha are all unable to be desulfurized.
2. According to my JEI in game, I found it out that to produce Light Fuel the only way is to distill Cracked Fuel, which is produced only after cracking those Fuel. That is an endless cycle.

**Test**
Case 1: I ran the game without SoG, and the recipe successfully exists in my JEI.
Case 2: I ran the game with SoG, and the recipe didn't exist.

**My Question**
Is that a new feature of SoG in newer version? Since it cancels the recipe, To upgrade to MV from LV is almost impossible, for it is unable to produce ethene, which is critical for making MV machines.
Or it is only a Bug? Whatever, I believe if this issue continues exist, the process to reach MV from LV is , well, quite complicated.

**Comment by ALongStringOfNumbers** [comment]
This was an unintentional change that happened during the previous release when I was cleaning up outdated recipe removals. It has since been fixed, and is waiting on a release for the recipes to be re-added. However, you can add them back yourself with Crafttweaker if that is desired.

**Comment by Exaxxion** [comment]
Closing since this issue was already fixed in #88
