### ISSUE TITLE
Update GTCE dependency to 1.13.0

### ISSUE THREAD

**Issue by Exaxxion** [Shadows-of-Fire/Shadows-of-Greg#116]
New version of GTCE released today. [Changelog here](https://github.com/GregTechCE/GregTech/commit/f0ee6248a7ee29177b326830561ffd1176ca7e75).

We should update to depend on it and merge #115 into it since the Chemistry Update Part 2 made it in, as well as address anything else that affects us from the change set so we can push a release.

**Comment by ALongStringOfNumbers** [comment]
We should take this opportunity to remove the addition and removal of liquid Iridium in the Fusion Reactor. We add this recipe in code, and then attempt to remove the same recipe. Therefore, it should most likely just be removed.
