### ISSUE TITLE
Cleanup Extra Classes

### ISSUE THREAD

**Issue by ALongStringOfNumbers** [Shadows-of-Fire/Shadows-of-Greg#120]
There are some classes that I am not sure if they are required anymore, due to removals in the mod, or changes in GTCE. I am making a list here for future investigation and commenting

1. [`SingleLimitFactory`](https://github.com/Shadows-of-Fire/Shadows-of-Greg/blob/master/src/main/java/gregicadditions/machines/SingleLimitFactory.java) This was originally implemented for some multiblocks, such as the Distillation Tower, however there does not seem to be any current use of the class in SoG code.
2. [`SingleLimitBlockPattern`](https://github.com/Shadows-of-Fire/Shadows-of-Greg/blob/master/src/main/java/gregicadditions/machines/SingleLimitBlockPattern.java) Similar to the class above, this was implemented for some multiblocks that have since been transported to GTCE, and has no current uses in SoG
3. [`NoEURecipeBuilder`](https://github.com/Shadows-of-Fire/Shadows-of-Greg/blob/master/src/main/java/gregicadditions/recipes/NoEURecipeBuilder.java) This was originally implemented for the Coke Oven, which has since been transferred to GTCE
4. [`FluidCellIngredient`](https://github.com/Shadows-of-Fire/Shadows-of-Greg/blob/master/src/main/java/gregicadditions/recipes/FluidCellIngredient.java) This is currently only being used in [Matter Replication](https://github.com/Shadows-of-Fire/Shadows-of-Greg/blob/master/src/main/java/gregicadditions/recipes/MatterReplication.java). This is one I am not quite sure about, as it is being used, but also I do not believe it is needed and can instead be replaced with something from GTCE
5. [`BasicMaterial`](https://github.com/Shadows-of-Fire/Shadows-of-Greg/blob/master/src/main/java/gregicadditions/item/BasicMaterial.java) This is no longer being used anymore. It was used previously to register Ultimet pipes, but is now no longer needed since Ultimet has been transferred to GTCE

**Comment by Exaxxion** [comment]
Fixed by #136
