### ISSUE TITLE
Slag Comb requires liquid lithium processing Crushed Lepidolite Ore

### ISSUE THREAD

**Issue by tonby** [Shadows-of-Fire/Shadows-of-Greg#156]
Generally, a GT comb processes a crushed ore and produces four purified ores and 144mb of liquid byproduct metal. Byproducts are determined as same as Ore Washer recipe.
Therefore, that recipe is expected:
9 * Slag Comb + Crushed Lepidolite Ore + 1000mb * Water -> 4 * Purified Lepidolite Ore + 144mb * Lithium (Liquid)
In fact, that recipe is registered:
9 * Slag Comb + Crushed Lepidolite Ore + 144mb * Lithium (Liquid) + 1000mb * Water -> 4 * Purified Lepidolite Ore
Liquid Lithium is resistered not as a byproduct, but as a requirement.

versions:
forge-14.23.5.2855
CodeChickenLib-1.12.2-3.2.3.358-universal.jar
forestry_1.12.2-5.8.2.422.jar
gregtech-1.12.2-1.16.1.753.jar
Shadows_of_Greg-1.12.2-2.19.0.jar
jei_1.12.2-4.16.1.302.jar

**Comment by warjort** [comment]
This looks like a typo here:

https://github.com/Shadows-of-Fire/Shadows-of-Greg/blob/2e96c448d605e599add739893ba6d220bf462dda/src/main/java/gregicadditions/bees/GTMachineCombRecipes.java#L95
