### ISSUE TITLE
incompatible with AoA

### ISSUE THREAD

**Issue by kotelkonrad** [Shadows-of-Fire/Shadows-of-Greg#19]
Mod Version
What version of the mod are you on?
latest

To Reproduce
Steps to reproduce the behaviour:
install shadows of greg and AoA
https://paste.dimdev.org/emotakugit.mccrash
![image](https://user-images.githubusercontent.com/48735640/56224894-a6a5d400-6070-11e9-8a0b-7eb8593f40c1.png)
Another links
Tslat/Advent-Of-Ascension#565
https://github.com/EmosewaPixel/GregicAdditions/issues/59

**Comment by Saereth** [comment]
looks like his crashlog is here, from the other thread
https://paste.dimdev.org/iqiyugecij.mccrash

**Comment by Saereth** [comment]
@kotelkonrad this is only a partial crashlog, can you post the full crashlog include gtce version as well as forge version

**Comment by kotelkonrad** [comment]
click with another links

**Comment by kotelkonrad** [comment]
or

**Comment by kotelkonrad** [comment]
[latest.log](https://github.com/Shadows-of-Fire/Shadows-of-Greg/files/3086102/latest.log)

**Comment by Shadows-of-Fire** [comment]
Judging by what tslat said I think he fixed this on his end, or it should be fixed in a newer aoa release.
