### ISSUE TITLE
[Crash] On Startup.

### ISSUE THREAD

**Issue by ScienceDrummer** [Shadows-of-Fire/Shadows-of-Greg#20]
VanillaFix says there's a problem with Shadow of Greg. Please correct me if wrong.

Crash: https://paste.dimdev.org/lozesocawu.rb

**Comment by eclcol** [comment]
I wanted to confirm this, my log is virtually identifical. However, if you roll back to the previous version of GTCE it doesn't crash, so the GTCE that was released a couple of days ago is causing the issue.

**Comment by Kehaan** [comment]
Just wanted to mention that i am getting the same crash.
[crash-2019-04-29_13.13.01-client.txt](https://github.com/Shadows-of-Fire/Shadows-of-Greg/files/3127167/crash-2019-04-29_13.13.01-client.txt)
