### ISSUE TITLE
Config to disable overclocking mechanics and deferring to base GTCE

### ISSUE THREAD

**Issue by Vyraal1** [Shadows-of-Fire/Shadows-of-Greg#21]
So GTCE just updated its overclocking mechanics, where instead of doubling its chances in SoG, it'll have a chanceTierBoost applied to each tier overclocked instead. Can we get a config to just disable SoG's overclocking or the section where it overrides? I have honestly no idea where to start on this so that's why I didn't wana webedit it.

**Comment by Shadows-of-Fire** [comment]
I don't really have any idea where that code is either, so uh...  Not sure what to do about this.

**Comment by Saereth** [comment]
base GTCE overclocking is broken right now, he's not even properly applying tierChance, once that is fixed, we're extending those base classes so Sog should just work fine with them but I'll verify once it's fixed

**Comment by Saereth** [comment]
base gtce covers this now with the tierChance recipe changes we added a while ago
