### ISSUE TITLE
[Crash] On Startup

### ISSUE THREAD

**Issue by ScienceDrummer** [Shadows-of-Fire/Shadows-of-Greg#25]
Hoping the crash report is correct in stating that this is the mod causing the crash.

Crash: https://paste.dimdev.org/feqofigina.mccrash

**Comment by PirateAdventurer** [comment]
I'm having the same problem and I also think it's coming from here. 

java.lang.NoSuchFieldError: toolHeadPlow

Log -https://paste.ee/p/M2oeN

**Comment by Shadows-of-Fire** [comment]
Closed via 1017e1a
