### ISSUE TITLE
What happened with some things from GA?

### ISSUE THREAD

**Issue by BlueCreeper160** [Shadows-of-Fire/Shadows-of-Greg#28]
I was playing my survival, and I seem some missing things, like the ultima dust, IV cables and limonite blast furnace recipe, and ores. that things were in GA, What happened to them? Will you add these things? (recipes and ores can be added with CT).

**Comment by Shadows-of-Fire** [comment]
Most content removed is now part of GTCE and is not necessary.  That said, anything gone is gone, and will not return.
