### ISSUE TITLE
All ring require small darmstadtium bending cylinder to craft.

### ISSUE THREAD

**Issue by Akiraca** [Shadows-of-Fire/Shadows-of-Greg#29]
![2019-05-17_21 07 15](https://user-images.githubusercontent.com/23720781/57924502-9475ba80-78e8-11e9-8c95-e391d1161898.png)

![2019-05-17_21 07 19](https://user-images.githubusercontent.com/23720781/57924549-b8390080-78e8-11e9-88f0-e459f7e087aa.png)

**Comment by MineTech123** [comment]
That’s a tool actually

**Comment by Saereth** [comment]
yeah this is not a valid issue. Also there is a config option to not require cylinders you can use should you wish
