### ISSUE TITLE
[Question+Suggestion+Idea] Plasma Generators 

### ISSUE THREAD

**Issue by MineTech123** [Shadows-of-Fire/Shadows-of-Greg#30]
Any plans on adding Plasma Generators from GT5?
In case if you’re confused with the Plasma Turbine I’m taking about these https://ftb.gamepedia.com/Plasma_Generator_(GregTech_5_Unofficial)
If so you can make like a low tier version of a plasma turbine

**Comment by Saereth** [comment]
we could but honestly this is the point of naquadah reactors, You convert energy from your plasma turbines or other sources into denser energy via naquadah and then can use the one-off generators. Making single block plasma gen would pretty much kill off naquadah gens usefulness entirely.
