### ISSUE TITLE
Macerator issues

### ISSUE THREAD

**Issue by robjw95** [Shadows-of-Fire/Shadows-of-Greg#37]
With the gtce 1.8.5 jei does not show uses for crushed ores or macerators

**Comment by gentwet** [comment]
it seems that  all the machines related recipes are broken in jei with the new gtce update when also using shadow of greg

**Comment by Blood-Asp** [comment]
Made PR for this (#38 ) There was still the recipemap for the cokeoven that is now added by GTCE. The recipemap was added double to JEI and crashed the addition of all other recipes to JEI.

**Comment by Shadows-of-Fire** [comment]
fbc668e
