### ISSUE TITLE
Materials/Items now redundant/deprecated with GTCE 1.6

### ISSUE THREAD

**Issue by Saereth** [Shadows-of-Fire/Shadows-of-Greg#4]
Circuit assembler (All tiers)
All circuits including all variants of circuits or any $circuitX oredict items 
supercomputers
mainframes
crystalcomputers
advanced alloy
mixed metal ingots
bick forms (all variants)
compressed fireclay
unfired clay brick

pretty much ALL the wafers
silicone boules (all variants)
raw carbon fiber
raw crystal chips
crystal processing unit
crystal SOC
lapotron crystals
iridium alloy plate
uncompressed iridium alloy plate
vacuum tube
all SMD components: transistor, resistor, capacitor, diode, small coil
electrical components: small coil, resistor, glass tube, capacitor, diode, vacuum tube
all circuit boards
stem cells

All of GA's materials except:
fish oil
CarbonMonoxde
RawGrowthMedium
SterilizedGrowthMedium
Meat
NeutralMatter
PositiveMatter
Neutronium
lignite coke
Extreme
Infinite

**Comment by Shadows-of-Fire** [comment]
All of these were removed, when GTCE pushes out the assembly line stuff, we can make another issue.
