### ISSUE TITLE
crash with gregtech ce 1.8.6.437

### ISSUE THREAD

**Issue by robjw95** [Shadows-of-Fire/Shadows-of-Greg#41]
new version of gregtech crashes with shadows of greg
[crash-2019-09-09_20.03.00-client.txt](https://github.com/Shadows-of-Fire/Shadows-of-Greg/files/3593061/crash-2019-09-09_20.03.00-client.txt)

**Comment by MasterEnderman** [comment]
it's caused by this line: https://github.com/Shadows-of-Fire/Shadows-of-Greg/blob/79c7be560b183671326a3735125af2fd4bb564b1/src/main/java/gregicadditions/recipes/MachineCraftingRecipes.java#L184

as they removed they removed the max voltage transformer.

**Comment by Shadows-of-Fire** [comment]
#42
