### ISSUE TITLE
Crash with gtce 1.8.9.457

### ISSUE THREAD

**Issue by magcicada** [Shadows-of-Fire/Shadows-of-Greg#47]
Crash with gtce 1.8.9.457

**Comment by Saereth** [comment]
crash log?

**Comment by MasterEnderman** [comment]
https://paste.dimdev.org/wasirodusa.mccrash

**Comment by LukaPix** [comment]
same here

**Comment by Blood-Asp** [comment]
Should be fixed with #48

**Comment by magcicada** [comment]
> 应该用[＃48](https://github.com/Shadows-of-Fire/Shadows-of-Greg/pull/48)固定[](https://github.com/Shadows-of-Fire/Shadows-of-Greg/pull/48)
Thanks a lot
