### ISSUE TITLE
Crashed with nuclearcraft and tconstruct loaded together

### ISSUE THREAD

**Issue by RCqaq** [Shadows-of-Fire/Shadows-of-Greg#51]
Since the Shadows_of_Greg 1.12.2-2.11.0, my minecraft crashed with nuclearcraft and tconstruct loaded.
Heres the crash report: [https://paste.ubuntu.com/p/zgRm9CTdRk/](url)

**Comment by Saereth** [comment]
yeah I noticed a similar crash with plusttic iridium, seems the gregworks code is registering materials without already checking if they are registered first.
