### ISSUE TITLE
Duplicate MarkerMaterials registered

### ISSUE THREAD

**Issue by Matryoshika** [Shadows-of-Fire/Shadows-of-Greg#6]
Minecraft Version: 1.12.2
Forge Version: 14.23.5.2811
GTCE Version: 1.6.2.189
SoG version: 2.0.0

I recently switched from GregicAdditions to Shadows Of Greg, but encountered this [issue](https://gist.github.com/Matryoshika/3cb1647daf67db4310f1f2f1ecbfa076) where the 'extreme' Marker Material has already been [registered by SoG](https://github.com/Shadows-of-Fire/Shadows-of-Greg/blob/master/src/main/java/gregicadditions/GAMaterials.java#L31) when [GTCE tries to register it itself](https://github.com/GregTechCE/GregTech/blob/1ea7ddfc8c1838148ea3c0af35e5a8540d66ccd9/src/main/java/gregtech/api/unification/material/MarkerMaterials.java#L94).

This would likely also happen for the 'infinite' Marker Material as well.

**Comment by Shadows-of-Fire** [comment]
SoG was last updated to GTCE 1.6.0.0, we're still working on what needs to be removed further, but we're waiting on a GTCE update that is supposed to bring the Assembly line and other GA stuff into GTCE.

**Comment by Shadows-of-Fire** [comment]
Closed as of 2.1.0
