### ISSUE TITLE
Could not add new classification 'genus.bees.fuelis', because the key is already taken by forestry.apiculture.genetics.BranchBees@7634d8c5.

### ISSUE THREAD

**Issue by trushoff** [Shadows-of-Fire/Shadows-of-Greg#67]
https://pastebin.com/NsVzkD4R

**Comment by Exaxxion** [comment]
I believe the issue here is that GTCE Bees was merged into Shadows of Greg [back in 2019](https://github.com/Shadows-of-Fire/Shadows-of-Greg/pull/40), and you are trying to use both GTCE Bees and Shadows of Greg.
