### ISSUE TITLE
Adding Multiblock Controllers to the input of the Processing Array crashes worlds

### ISSUE THREAD

**Issue by ALongStringOfNumbers** [Shadows-of-Fire/Shadows-of-Greg#71]
GTCE: 1.10.1.557
SoG: 2.14
Forge: 1.12 - 2847

Adding mutliblock controllers to the input of a Processing Array will crash the world. Some example crashes are:

Electric Blast Furnace Controller: [https://pastebin.com/LWYE2iKM](url)

The Processing Array Controller, Assembly Line controller, and others.

This did not occur when a fusion reactor controller was used (For any tier of fusion reactor)

**Comment by phantamanta44** [comment]
the check for whether the processing machine is a machine [as implemented here](https://github.com/Shadows-of-Fire/Shadows-of-Greg/blob/master/src/main/java/gregicadditions/machines/TileEntityProcessingArray.java#L366) is insufficient; the check should ensure that it's not only a machine, but that it has a well-defined voltage so the [implicit unboxing operation here](https://github.com/Shadows-of-Fire/Shadows-of-Greg/blob/master/src/main/java/gregicadditions/machines/TileEntityProcessingArray.java#L372) doesn't throw an NPE
