### ISSUE TITLE
[Suggestion] Make crates the same size as chests

### ISSUE THREAD

**Issue by Bombm** [Shadows-of-Fire/Shadows-of-Greg#86]
Sometimes when making automation lines it gets very hard to remove/edit covers from machines or crates if direct outputting. Making the crates smaller would be very helpful as any side of the crate would be accessful.
Probably it's not possible as it would cause bugs with covers, but maybe some other solution is possible?

**Comment by Exaxxion** [comment]
Obscured faces of GTCE machines (which includes our crates) are accessible using the access grid on them that appears while you hold a cover or machine tool like a screwdriver or wrench.

If I'm misunderstanding your suggestion, please feel free to clarify.
