### ISSUE TITLE
[Suggestion] Increase single-block machines that can be compacted by a processing array to 64 to match GT5U

### ISSUE THREAD

**Issue by Rafmaninoff** [Shadows-of-Fire/Shadows-of-Greg#95]
Title. Another idea could be leaving the current one alone and creating an Advanced Processing Array for tiering purposes.

**Comment by Exaxxion** [comment]
This isn't difficult to do from a code standpoint, but does have gameplay balance implications. You'd be reducing the cost and space requirements of setting up equivalent infrastructure by roughly 75%.

I'm not entirely sure this is desirable.

**Comment by Rafmaninoff** [comment]
Same logic could be applied to the current PA, it reduces space requirement of setting up infrastructure by a lot. and, say you're using a PA for autocrafting, Robs you of the joy™ of having to share items among multiple machines so they all get utilised evenly.

maybe the recipe could involve UV-tier parts and the multiblock need to be built out of much higher end materials, say HSS-E instead of tungstensteel.

**Comment by Rafmaninoff** [comment]
Another option is making the maximum machines per PA or APA a config option that packmakers can set
